- dashboard: converted_dash
  title: converted_dash
  layout: newspaper
  preferred_viewer: dashboards-next
  description: Autogenerated
  elements:
  - title: look number = 3
    name: look number = 3
    model: crime
    explore: crime
    type: looker_pie
    fields: [crime.description, crime.count_events]
    sorts: [crime.count_events desc]
    limit: 10
    query_timezone: America/Los_Angeles
    value_labels: legend
    label_type: labPer
    x_axis_gridlines: false
    y_axis_gridlines: true
    show_view_names: false
    show_y_axis_labels: true
    show_y_axis_ticks: true
    y_axis_tick_density: default
    y_axis_tick_density_custom: 5
    show_x_axis_label: true
    show_x_axis_ticks: true
    y_axis_scale_mode: linear
    x_axis_reversed: false
    y_axis_reversed: false
    plot_size_by_field: false
    trellis: ''
    stacking: ''
    limit_displayed_rows: false
    legend_position: center
    point_style: none
    show_value_labels: false
    label_density: 25
    x_axis_scale: auto
    y_axis_combined: true
    show_null_points: true
    interpolation: linear
    show_totals_labels: false
    show_silhouette: false
    totals_color: "#808080"
    show_row_numbers: true
    truncate_column_names: false
    hide_totals: false
    hide_row_totals: false
    table_theme: editable
    enable_conditional_formatting: false
    conditional_formatting_include_totals: false
    conditional_formatting_include_nulls: false
    defaults_version: 1
    series_types: {}
    ordering: none
    show_null_labels: false
    row: 2
    col: 0
    width: 8
    height: 6
  - title: look number = 4
    name: look number = 4
    model: the_look
    explore: order_items
    type: table
    fields: [orders.created_quarter, order_items.total_sale_price]
    fill_fields: [orders.created_quarter]
    sorts: [orders.created_quarter desc]
    limit: 500
    query_timezone: America/Los_Angeles
    show_view_names: false
    show_row_numbers: true
    truncate_column_names: false
    hide_totals: false
    hide_row_totals: false
    table_theme: editable
    limit_displayed_rows: false
    enable_conditional_formatting: false
    conditional_formatting_include_totals: false
    conditional_formatting_include_nulls: false
    defaults_version: 1
    row: 2
    col: 8
    width: 8
    height: 6
  - name: ''
    type: text
    title_text: ''
    subtitle_text: ''
    body_text: |-
      <div style="border-radius: 5px; padding: 5px 10px; background: #412399; height: 60px; color: red;">
      <nav style="font-size: 18px;">
        <img style="color: #efefef; padding: 5px 15px; float: left; height: 40px;" src="https://wwwstatic.lookercdn.com/logos/looker_all_white.svg"/>
        <a style="color: #efefef; padding: 5px 15px; float: left; line-height: 40px; font-weight: bold;" href="#home">☰
       Home</a>
        <a style="color: #efefef; padding: 5px 15px; float: left; line-height: 40px;" href="#news">News</a>
        <a style="color: #efefef; padding: 5px 15px; float: left; line-height: 40px;" href="#contact">Contact</a>
        <a style="color: #efefef; padding: 5px 15px; float: left; line-height: 40px;" href="#about">About</a>
      </nav>
      </div>
    row: 0
    col: 0
    width: 24
    height: 2
  - name: " (2)"
    type: text
    title_text: ''
    subtitle_text: ''
    body_text: "<div style=\"font-size: 18px; padding: 5px 10px 0 10px;\">\n\t<a style='display:\
      \ block; border-radius: 5px; padding: 5px 10px; margin-bottom: 10px; font-weight:\
      \ bold; background-color: #eaf1fe; border: solid 1px #4285F4;' href=\"#\">Home</a>\n\
      \t<a style='display: block; border-radius: 5px; padding: 5px 10px; margin-bottom:\
      \ 10px;' href=\"#\">Business Pulse</a>\n\t<a style='display: block; border-radius:\
      \ 5px; padding: 5px 10px; margin-bottom: 10px;' href=\"#\">Demographics</a>\n\
      \t<a style='display: block; border-radius: 5px; padding: 5px 10px; margin-bottom:\
      \ 10px;' href=\"#\">Web Analytics</a>\n</div>"
    row:
    col:
    width:
    height:
  - name: " (3)"
    type: text
    title_text: ''
    subtitle_text: ''
    body_text: |2-

      <nav style="font-size: 18px; padding: 5px 10px 0 10px; height: 60px">
        <a style="padding: 5px; border-top: solid 1px #4285F4; border-left: solid 1px #4285F4; border-right: solid 1px #4285F4; border-radius: 5px 5px 0 0; float: left; line-height: 40px; font-weight: bold;" href="#home">
      Home</a>
        <a style="padding: 5px; border-bottom: solid 1px #4285F4; float: left; line-height: 40px;" href="#news">News</a>
        <a style="padding: 5px; border-bottom: solid 1px #4285F4; float: left; line-height: 40px;" href="#contact">Contact</a>
        <a style="padding: 5px; border-bottom: solid 1px #4285F4; float: left; line-height: 40px;" href="#about">About</a>
      </nav>
    row:
    col:
    width:
    height:
  - title: New Tile
    name: New Tile
    model: system__activity
    explore: scheduled_plan
    type: looker_pie
    fields: [scheduled_job.created_day_of_week, scheduled_job.count]
    fill_fields: [scheduled_job.created_day_of_week]
    filters:
      scheduled_plan.run_once: 'No'
      scheduled_job.created_date: 7 days ago for 7 days
    sorts: [scheduled_job.created_day_of_week]
    limit: 500
    query_timezone: America/Los_Angeles
    value_labels: legend
    label_type: lab
    inner_radius: 50
    colors: ["#75E2E2", "#3EB0D5", "#4276BE", "#462C9D", "#9174F0", "#B1399E", "#B32F37",
      "#E57947", "#FBB555", "#FFD95F", "#C2DD67", "#72D16D"]
    series_colors: {}
    custom_color_enabled: false
    custom_color: forestgreen
    show_single_value_title: true
    show_comparison: true
    comparison_type: change
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: Last 30 Days
    hidden_fields:
    series_types: {}
    note_state: collapsed
    note_display: hover
    note_text: Number of scheduled jobs each day for last 7 days. One scheduled plan
      may have multiple scheduled jobs.
    defaults_version: 1
    row:
    col:
    width:
    height:
